### ISSUE TITLE
Broken MANIFEST

### ISSUE THREAD

**Issue by Grinnz** [davorg/template-provider-pandoc#4]
The module file was not included in your latest upload as MANIFEST is still pointing to the old module location.

**Comment by Grinnz** [comment]
By the way if you are intending to deprecate Template::Provider::Markdown::Pandoc then take a look at http://neilb.org/2015/01/17/deprecated-metadata.html

**Comment by davorg** [comment]
Thanks. Version 0.0.2 is now en route to CPAN.

I'll probably just delete Template::Provider::Markdown::Pandoc from CPAN. I don't think anyone but me ever used it.
